name: pre-commit

on:
  workflow_call:

permissions: {}

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.1

  husky:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: npm ci
      - name: Run npm style-checks
        run: |
          npm run format
          npm run lint

  check-dist:
    permissions:
      contents: write # git push
      actions: write # re-trigger CI workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # For EndBug/add-and-commit to work with PRs
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20
      - run: npm ci
      - name: Rebuild the dist/ directory
        run: |
          npm run build
          npm run package

      - uses: EndBug/add-and-commit@v9
        id: commit
        with:
          add: dist/
          message: "chore: Rebuild `dist/`"
          default_author: github_actions
      - name: Retrigger CI workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh workflow run ci.yaml --repo ${{ github.repository }}
        if: steps.commit.outputs.committed == 'true'
